In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("multiple_linear_regression_30_rows.csv")
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0       62781          138635           439142    New York   70418.76
1      100802           80430           291989     Florida   91787.87
2       67828           86346           422700    New York   61036.32
3      167958           87591           236290  California  133252.92
4      102445          128469           299486    New York   98493.96
5      103220          153716           113629    New York   87251.19
6       90838          139036           241368    New York   75155.16
7      111857           84987           417665    New York   96904.29
8       83659          125239            30492    New York   62196.74
9      130802           81975            57351  California  116338.63
10     107574           86007            68526     Florida   97903.12
11     138803          107708           196177     Florida  117811.87
12     155045          139194           128722  California  140054.54
13     124146          132721           341720  California  117945.82
14      82039           88550           344278     Florida   81842.54
15     135057          153332            30615  California  115125.69
16      64749          151557           347773    New York   61638.53
17      80051           98170            17919  California   62730.77
18      84402          155713            96876  California   79846.14
19     140409          131955           306772    New York  125805.46
20      62625          151696           393367  California   60150.93
21     148632          117220           127708     Florida  129433.24
22      75038          140424            73802     Florida   73369.94
23     107900          129773            46041  California   84018.69
24      73587          104888           110963    New York   58552.25
25     102003          144755           157132    New York   93961.46
26     136838          110293           263973     Florida  113395.45
27     163767          127186            96202  California  129103.38
28     145807          141404           264868    New York  124152.72
29      64489          112859            94189  California   65278.05

In [14]:
dataset = pd.get_dummies(dataset, drop_first=True).astype(int)

In [12]:
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_California,State_Florida,State_New York
0,62781,138635,439142,70418,0,0,1
1,100802,80430,291989,91787,0,1,0
2,67828,86346,422700,61036,0,0,1
3,167958,87591,236290,133252,1,0,0
4,102445,128469,299486,98493,0,0,1
5,103220,153716,113629,87251,0,0,1
6,90838,139036,241368,75155,0,0,1
7,111857,84987,417665,96904,0,0,1
8,83659,125239,30492,62196,0,0,1
9,130802,81975,57351,116338,1,0,0
10,107574,86007,68526,97903,0,1,0
11,138803,107708,196177,117811,0,1,0
12,155045,139194,128722,140054,1,0,0
13,124146,132721,341720,117945,1,0,0
14,82039,88550,344278,81842,0,1,0
15,135057,153332,30615,115125,1,0,0
16,64749,151557,347773,61638,0,0,1
17,80051,98170,17919,62730,1,0,0
18,84402,155713,96876,79846,1,0,0
19,140409,131955,306772,125805,0,0,1
20,62625,151696,393367,60150,1,0,0
21,148632,117220,127708,129433,0,1,0
22,75038,140424,73802,73369,0,1,0
23,107900,129773,46041,84018,1,0,0
24,73587,104888,110963,58552,0,0,1
25,102003,144755,157132,93961,0,0,1
26,136838,110293,263973,113395,0,1,0
27,163767,127186,96202,129103,1,0,0
28,145807,141404,264868,124152,0,0,1
29,64489,112859,94189,65278,1,0,0

In [15]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_California', 'State_Florida', 'State_New York'],
      dtype='object')

In [23]:
independent= dataset[['R&D Spend', 'Administration', 'Marketing Spend',
       'State_California', 'State_Florida', 'State_New York']]

In [24]:
independent

,R&D Spend,Administration,Marketing Spend,State_California,State_Florida,State_New York
0,62781,138635,439142,0,0,1
1,100802,80430,291989,0,1,0
2,67828,86346,422700,0,0,1
3,167958,87591,236290,1,0,0
4,102445,128469,299486,0,0,1
5,103220,153716,113629,0,0,1
6,90838,139036,241368,0,0,1
7,111857,84987,417665,0,0,1
8,83659,125239,30492,0,0,1
9,130802,81975,57351,1,0,0
10,107574,86007,68526,0,1,0
11,138803,107708,196177,0,1,0
12,155045,139194,128722,1,0,0
13,124146,132721,341720,1,0,0
14,82039,88550,344278,0,1,0
15,135057,153332,30615,1,0,0
16,64749,151557,347773,0,0,1
17,80051,98170,17919,1,0,0
18,84402,155713,96876,1,0,0
19,140409,131955,306772,0,0,1
20,62625,151696,393367,1,0,0
21,148632,117220,127708,0,1,0
22,75038,140424,73802,0,1,0
23,107900,129773,46041,1,0,0
24,73587,104888,110963,0,0,1
25,102003,144755,157132,0,0,1
26,136838,110293,263973,0,1,0
27,163767,127186,96202,1,0,0
28,145807,141404,264868,0,0,1
29,64489,112859,94189,1,0,0

In [26]:
dependent=dataset[["Profit"]]

In [27]:
dependent

    Profit
0    70418
1    91787
2    61036
3   133252
4    98493
5    87251
6    75155
7    96904
8    62196
9   116338
10   97903
11  117811
12  140054
13  117945
14   81842
15  115125
16   61638
17   62730
18   79846
19  125805
20   60150
21  129433
22   73369
23   84018
24   58552
25   93961
26  113395
27  129103
28  124152
29   65278

In [29]:
#train model
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [32]:
#learn 
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [33]:
weight=regressor.coef_
weight

array([[ 7.93475263e-01,  6.59158718e-02,  2.31690513e-02,
        -3.75918498e+02,  3.51643877e+03, -3.14052027e+03]])

In [34]:
bias=regressor.intercept_
bias

array([-1930.74218875])

In [35]:
#evaluation
y_pred=regressor.predict(x_test)

In [36]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.9535418948669916

In [37]:
import pickle
filename="finalized_model_mul_linear.sav"
pickle.dump(regressor,open(filename,"wb"))

In [39]:
load_model=pickle.load(open("finalized_model_mul_linear.sav",'rb'))

In [42]:
result=load_model.predict([[3.333,4.444,5.555,2.222,2.333,989.8888]])

C:\Users\SATHYABOOPALAN\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [43]:
result

array([[-3103324.96113111]])